import { ensureSchema, getSql, hasDatabaseUrl, devReceiptNumber, nextReceiptNumber } from '../db';
import { isProduction, memoryStoreAllowed } from '../config';
import { computeProcessingFee } from '../../shared/fees';
import type pg from 'pg';

export type GiftFrequency = 'one-time' | 'weekly' | 'bi-weekly' | 'monthly' | 'annually';
export type GiftPaymentMethod =
  | 'card'
  | 'ach'
  | 'apple_pay'
  | 'cash'
  | 'check'
  | 'cash_app'
  | 'zelle'
  | 'venmo'
  | 'us_bank_account';

export interface StoredDonor {
  id: string;
  name: string;
  email: string;
  phone: string;
  address: string;
  taxId?: string;
  lifetimeGiving: number;
  totalGiftsCount: number;
  firstGiftDate: string;
  lastGiftDate: string;
  recurringActive: boolean;
  recurringAmount?: number;
  recurringFrequency?: GiftFrequency;
  gdprConsent: boolean;
  gdprConsentDate: string;
  isAnonymized?: boolean;
  stripeCustomerId?: string;
  stripeSubscriptionId?: string;
}

export interface StoredDonation {
  id: string;
  transactionId: string;
  receiptNumber: string;
  donorId: string;
  donorName: string;
  donorEmail: string;
  donorAddress?: string;
  amount: number;
  feeCovered: boolean;
  feeAmount: number;
  totalCharged: number;
  frequency: GiftFrequency;
  fundId: string;
  fundName: string;
  fundCode: string;
  paymentMethod: GiftPaymentMethod;
  cardBrand?: string;
  cardLast4?: string;
  status: 'completed' | 'pending' | 'refunded' | 'failed';
  refundedAmount: number;
  dedication?: string;
  isAnonymous: boolean;
  timestamp: string;
  nextBillingDate?: string;
  stripePaymentIntentId?: string;
  plaidTransferId?: string;
  plaidInstitution?: string;
  plaidAccountMask?: string;
  awcDcbVoucher?: string;
  awcSynced: boolean;
  encryptedToken: string;
  envelopeNumber?: string;
}

export interface CreateGiftInput {
  amount: number;
  feeCovered: boolean;
  feeAmount?: number;
  frequency: GiftFrequency;
  fundId: string;
  fundName: string;
  fundCode?: string;
  donorName: string;
  donorEmail: string;
  donorAddress?: string;
  paymentMethod: GiftPaymentMethod;
  cardBrand?: string;
  cardLast4?: string;
  dedication?: string;
  isAnonymous?: boolean;
  stripePaymentIntentId?: string;
  awcDcbVoucher?: string;
  awcSynced?: boolean;
  transactionId?: string;
  contributedAt?: string;
  /** Defaults to completed. */
  status?: StoredDonation['status'];
  stripeCustomerId?: string;
  /** Stripe subscription current_period_end. Never computed locally. */
  nextBillingDate?: string | null;
  stripeSubscriptionId?: string;
  /**
   * Pre-allocated receipt number from the Postgres sequence.
   * Required in production (generated by handleWebhook inside the pg transaction).
   * Falls back to devReceiptNumber() in dev/memory mode only.
   */
  receiptNumber?: string;
  pgClient?: pg.PoolClient;
}

const memoryDonors = new Map<string, StoredDonor>();
const memoryDonations: StoredDonation[] = [];

function requireMemoryGifts(): void {
  if (!memoryStoreAllowed()) {
    throw new Error('DATABASE_URL is required unless DEV_MEMORY_STORE=true');
  }
}

function normalizeEmail(email: string): string {
  return email.trim().toLowerCase();
}

function num(value: unknown, fallback = 0): number {
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function mapDonorRow(row: Record<string, unknown>): StoredDonor {
  return {
    id: String(row.id),
    name: String(row.name),
    email: String(row.email),
    phone: String(row.phone || ''),
    address: String(row.address || ''),
    taxId: row.tax_id ? String(row.tax_id) : undefined,
    lifetimeGiving: num(row.lifetime_giving),
    totalGiftsCount: Number(row.total_gifts_count || 0),
    firstGiftDate: new Date(String(row.first_gift_date)).toISOString(),
    lastGiftDate: new Date(String(row.last_gift_date)).toISOString(),
    recurringActive: Boolean(row.recurring_active),
    recurringAmount: row.recurring_amount != null ? num(row.recurring_amount) : undefined,
    recurringFrequency: row.recurring_frequency
      ? (String(row.recurring_frequency) as GiftFrequency)
      : undefined,
    gdprConsent: Boolean(row.gdpr_consent),
    gdprConsentDate: new Date(String(row.gdpr_consent_date || row.first_gift_date)).toISOString(),
    isAnonymized: Boolean(row.is_anonymized),
    stripeCustomerId: row.stripe_customer_id ? String(row.stripe_customer_id) : undefined,
  };
}

function mapDonationRow(row: Record<string, unknown>): StoredDonation {
  return {
    id: String(row.id),
    transactionId: String(row.transaction_id),
    receiptNumber: String(row.receipt_number),
    donorId: String(row.donor_id),
    donorName: String(row.donor_name),
    donorEmail: String(row.donor_email),
    donorAddress: row.donor_address ? String(row.donor_address) : undefined,
    amount: num(row.amount),
    feeCovered: Boolean(row.fee_covered),
    feeAmount: num(row.fee_amount),
    totalCharged: num(row.total_charged),
    frequency: String(row.frequency) as GiftFrequency,
    fundId: String(row.fund_id),
    fundName: String(row.fund_name),
    fundCode: String(row.fund_code || ''),
    paymentMethod: String(row.payment_method) as GiftPaymentMethod,
    cardBrand: row.card_brand ? String(row.card_brand) : undefined,
    cardLast4: row.card_last4 ? String(row.card_last4) : undefined,
    status: String(row.status || 'completed') as StoredDonation['status'],
    refundedAmount: num(row.refunded_amount),
    dedication: row.dedication ? String(row.dedication) : undefined,
    isAnonymous: Boolean(row.is_anonymous),
    timestamp: new Date(String(row.contributed_at)).toISOString(),
    nextBillingDate: row.next_billing_date
      ? new Date(String(row.next_billing_date)).toISOString()
      : undefined,
    stripePaymentIntentId: row.stripe_payment_intent_id
      ? String(row.stripe_payment_intent_id)
      : undefined,
    plaidTransferId: row.plaid_transfer_id ? String(row.plaid_transfer_id) : undefined,
    plaidInstitution: row.plaid_institution ? String(row.plaid_institution) : undefined,
    plaidAccountMask: row.plaid_account_mask ? String(row.plaid_account_mask) : undefined,
    awcDcbVoucher: row.awc_dcb_voucher ? String(row.awc_dcb_voucher) : undefined,
    awcSynced: Boolean(row.awc_synced),
    encryptedToken: String(row.encrypted_token || ''),
    envelopeNumber: row.envelope_number ? String(row.envelope_number) : undefined,
  };
}

export async function initGiftStore(): Promise<{ mode: 'neon' | 'memory'; error?: string }> {
  const result = await ensureSchema();
  if (result.mode === 'memory' && !memoryStoreAllowed()) {
    console.error('[gifts] DATABASE_URL is required unless DEV_MEMORY_STORE=true (forbidden in production).');
    process.exit(1);
  }
  return { mode: result.mode, error: result.error };
}

export function giftStoreMode(): 'neon' | 'memory' {
  return hasDatabaseUrl() ? 'neon' : 'memory';
}

async function findDonorByEmailNeon(email: string): Promise<StoredDonor | null> {
  const client = getSql();
  if (!client) return null;
  const rows = await client`
    SELECT * FROM donors WHERE LOWER(email) = ${normalizeEmail(email)} LIMIT 1
  `;
  if (!rows.length) return null;
  return mapDonorRow(rows[0] as Record<string, unknown>);
}

function findDonorByEmailMemory(email: string): StoredDonor | null {
  const normalized = normalizeEmail(email);
  for (const donor of memoryDonors.values()) {
    if (normalizeEmail(donor.email) === normalized) return donor;
  }
  return null;
}

/** Lifetime totals are derived from completed donation rows, not a running counter. */
export async function refreshDonorAggregates(donorId: string): Promise<void> {
  const client = getSql();
  if (!client || !donorId) return;
  await client`
    UPDATE donors SET
      lifetime_giving = COALESCE((
        SELECT SUM(amount) FROM donations WHERE donor_id = ${donorId} AND status = 'completed'
      ), 0),
      total_gifts_count = COALESCE((
        SELECT COUNT(*)::int FROM donations WHERE donor_id = ${donorId} AND status = 'completed'
      ), 0),
      updated_at = NOW()
    WHERE id = ${donorId}
  `;
}

async function refreshDonorAggregatesInTransaction(
  client: pg.PoolClient,
  donorId: string
): Promise<void> {
  await client.query(
    `UPDATE donors SET
      lifetime_giving = COALESCE((
        SELECT SUM(amount) FROM donations WHERE donor_id = $1 AND status = 'completed'
      ), 0),
      total_gifts_count = COALESCE((
        SELECT COUNT(*)::int FROM donations WHERE donor_id = $1 AND status = 'completed'
      ), 0),
      updated_at = NOW()
    WHERE id = $1`,
    [donorId]
  );
}

export async function recomputeAllDonorTotals(apply: boolean): Promise<{
  mode: 'neon' | 'memory';
  changes: Array<{
    email: string;
    lifetimeGiving: number;
    totalGiftsCount: number;
    nextLifetime: number;
    nextCount: number;
  }>;
}> {
  const client = getSql();
  if (!client) {
    requireMemoryGifts();
    const changes = [];
    for (const donor of memoryDonors.values()) {
      const rows = memoryDonations.filter((d) => d.donorId === donor.id && d.status === 'completed');
      const nextLifetime = rows.reduce((s, d) => s + d.amount, 0);
      const nextCount = rows.length;
      if (nextLifetime !== donor.lifetimeGiving || nextCount !== donor.totalGiftsCount) {
        changes.push({
          email: donor.email,
          lifetimeGiving: donor.lifetimeGiving,
          totalGiftsCount: donor.totalGiftsCount,
          nextLifetime,
          nextCount,
        });
        if (apply) {
          donor.lifetimeGiving = nextLifetime;
          donor.totalGiftsCount = nextCount;
        }
      }
    }
    return { mode: 'memory', changes };
  }

  const rows = await client`
    SELECT d.id, d.email, d.lifetime_giving, d.total_gifts_count,
      COALESCE((SELECT SUM(amount) FROM donations g WHERE g.donor_id = d.id AND g.status = 'completed'), 0) AS next_lifetime,
      COALESCE((SELECT COUNT(*)::int FROM donations g WHERE g.donor_id = d.id AND g.status = 'completed'), 0) AS next_count
    FROM donors d
  `;
  const changes = [];
  for (const row of rows) {
    const lifetimeGiving = num(row.lifetime_giving);
    const totalGiftsCount = num(row.total_gifts_count);
    const nextLifetime = num(row.next_lifetime);
    const nextCount = num(row.next_count);
    if (lifetimeGiving !== nextLifetime || totalGiftsCount !== nextCount) {
      changes.push({
        email: String(row.email),
        lifetimeGiving,
        totalGiftsCount,
        nextLifetime,
        nextCount,
      });
    }
  }
  if (apply && changes.length) {
    await client`
      UPDATE donors d SET
        lifetime_giving = COALESCE((SELECT SUM(amount) FROM donations g WHERE g.donor_id = d.id AND g.status = 'completed'), 0),
        total_gifts_count = COALESCE((SELECT COUNT(*)::int FROM donations g WHERE g.donor_id = d.id AND g.status = 'completed'), 0),
        updated_at = NOW()
    `;
  }
  return { mode: 'neon', changes };
}

export async function createGift(input: CreateGiftInput): Promise<{
  donor: StoredDonor;
  donation: StoredDonation;
  mode: 'neon' | 'memory';
  inserted: boolean;
  becameCompleted: boolean;
  becameFailed: boolean;
}> {
  const now = input.contributedAt ? new Date(input.contributedAt) : new Date();
  const timestamp = now.toISOString();
  const email = normalizeEmail(input.donorEmail);
  if (!email || !email.includes('@')) {
    throw new Error('A valid donor email is required');
  }
  if (!Number.isFinite(input.amount) || input.amount <= 0) {
    throw new Error('Gift amount must be greater than zero');
  }

  // Authoritative fee math — ignore client-supplied feeAmount for charging
  const computed = computeProcessingFee({
    principal: input.amount,
    method: input.paymentMethod,
    coverFees: Boolean(input.feeCovered),
  });
  const feeAmount = computed.feeAmount;
  const totalCharged = computed.totalCharged;
  const giftStatus: StoredDonation['status'] = input.status || 'completed';
  const isAnonymous = Boolean(input.isAnonymous);
  const displayName = isAnonymous ? 'Anonymous' : input.donorName.trim() || 'Anonymous';

  const nextBillingDate = input.nextBillingDate || null;

  const transactionId =
    input.transactionId ||
    input.stripePaymentIntentId ||
    `txn_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;

  let receiptNumber = input.receiptNumber || devReceiptNumber(now.getFullYear());
  const donationId = `don-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
  const fundCode = input.fundCode || '';

  const client = getSql();
  const mode = client ? 'neon' : 'memory';

  if (input.pgClient) {
    const tx = input.pgClient;
    const existingResult = await tx.query(
      'SELECT * FROM donations WHERE transaction_id = $1 LIMIT 1 FOR UPDATE',
      [transactionId]
    );
    if (existingResult.rows.length) {
      let row = existingResult.rows[0] as Record<string, unknown>;
      const wasCompleted = String(row.status) === 'completed';
      const wasPending = String(row.status) === 'pending';
      if ((giftStatus === 'completed' && !wasCompleted) || (giftStatus === 'failed' && wasPending)) {
        const updated = await tx.query(
          giftStatus === 'completed'
            ? `UPDATE donations SET
                status = 'completed', amount = $2, fee_covered = $3, fee_amount = $4,
                total_charged = $5, payment_method = $6,
                stripe_payment_intent_id = COALESCE($7, stripe_payment_intent_id),
                next_billing_date = COALESCE($8, next_billing_date)
              WHERE transaction_id = $1 RETURNING *`
            : "UPDATE donations SET status = 'failed' WHERE transaction_id = $1 RETURNING *",
          giftStatus === 'completed'
            ? [
                transactionId,
                input.amount,
                input.feeCovered,
                feeAmount,
                totalCharged,
                input.paymentMethod,
                input.stripePaymentIntentId || null,
                nextBillingDate,
              ]
            : [transactionId]
        );
        row = updated.rows[0] as Record<string, unknown>;
        if (giftStatus === 'completed') {
          await refreshDonorAggregatesInTransaction(tx, String(row.donor_id));
        }
      }
      const donorResult = await tx.query('SELECT * FROM donors WHERE id = $1 LIMIT 1', [row.donor_id]);
      return {
        donor: mapDonorRow(donorResult.rows[0] as Record<string, unknown>),
        donation: mapDonationRow(row),
        mode: 'neon',
        inserted: false,
        becameCompleted: giftStatus === 'completed' && !wasCompleted,
        becameFailed: giftStatus === 'failed' && wasPending,
      };
    }

    if (!input.receiptNumber) {
      receiptNumber = await nextReceiptNumber(tx, now.getFullYear());
    }
    const donorId = `donor-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const donorResult = await tx.query(
      `INSERT INTO donors (
        id, name, email, phone, address, lifetime_giving, total_gifts_count,
        first_gift_date, last_gift_date, recurring_active, recurring_amount,
        recurring_frequency, gdpr_consent, gdpr_consent_date, stripe_customer_id,
        stripe_subscription_id
      ) VALUES (
        $1, $2, $3, '', $4, 0, 0, $5, $5, $6, $7, $8, TRUE, $5, $9, $10
      )
      ON CONFLICT (email) DO UPDATE SET
        name = CASE WHEN $11 THEN donors.name ELSE EXCLUDED.name END,
        address = CASE WHEN $4 = '' THEN donors.address ELSE EXCLUDED.address END,
        last_gift_date = EXCLUDED.last_gift_date,
        recurring_active = CASE WHEN $12 THEN TRUE ELSE donors.recurring_active END,
        recurring_amount = CASE WHEN $12 THEN EXCLUDED.recurring_amount ELSE donors.recurring_amount END,
        recurring_frequency = CASE WHEN $12 THEN EXCLUDED.recurring_frequency ELSE donors.recurring_frequency END,
        stripe_customer_id = COALESCE(EXCLUDED.stripe_customer_id, donors.stripe_customer_id),
        stripe_subscription_id = COALESCE(EXCLUDED.stripe_subscription_id, donors.stripe_subscription_id),
        updated_at = NOW()
      RETURNING *`,
      [
        donorId,
        displayName,
        email,
        input.donorAddress || '',
        timestamp,
        input.frequency !== 'one-time',
        input.frequency !== 'one-time' ? input.amount : null,
        input.frequency !== 'one-time' ? input.frequency : null,
        input.stripeCustomerId || null,
        input.stripeSubscriptionId || null,
        isAnonymous,
        input.frequency !== 'one-time',
      ]
    );
    const donor = mapDonorRow(donorResult.rows[0] as Record<string, unknown>);

    const insertedResult = await tx.query(
      `INSERT INTO donations (
        id, transaction_id, receipt_number, donor_id, donor_name, donor_email, donor_address,
        amount, fee_covered, fee_amount, total_charged, frequency, fund_id, fund_name, fund_code,
        payment_method, card_brand, card_last4, status, dedication, is_anonymous, contributed_at,
        next_billing_date, stripe_payment_intent_id, plaid_transfer_id, plaid_institution,
        plaid_account_mask, awc_dcb_voucher, awc_synced, encrypted_token, envelope_number
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
        $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, '', NULL
      )
      ON CONFLICT (transaction_id) DO NOTHING
      RETURNING *`,
      [
        donationId,
        transactionId,
        receiptNumber,
        donor.id,
        displayName,
        email,
        input.donorAddress || null,
        input.amount,
        input.feeCovered,
        feeAmount,
        totalCharged,
        input.frequency,
        input.fundId,
        input.fundName,
        fundCode,
        input.paymentMethod,
        input.cardBrand || null,
        input.cardLast4 || null,
        giftStatus,
        input.dedication || null,
        isAnonymous,
        timestamp,
        nextBillingDate,
        input.stripePaymentIntentId || null,
        null,
        null,
        null,
        input.awcDcbVoucher || null,
        Boolean(input.awcSynced),
      ]
    );
    const inserted = insertedResult.rows.length > 0;
    const finalRow = inserted
      ? (insertedResult.rows[0] as Record<string, unknown>)
      : (await tx.query('SELECT * FROM donations WHERE transaction_id = $1 LIMIT 1', [transactionId])).rows[0] as Record<string, unknown>;
    if (inserted && giftStatus === 'completed') {
      await refreshDonorAggregatesInTransaction(tx, donor.id);
    }
    const refreshedDonor = giftStatus === 'completed'
      ? await tx.query('SELECT * FROM donors WHERE id = $1 LIMIT 1', [donor.id])
      : null;
    return {
      donor: refreshedDonor
        ? mapDonorRow(refreshedDonor.rows[0] as Record<string, unknown>)
        : donor,
      donation: mapDonationRow(finalRow),
      mode: 'neon',
      inserted,
      becameCompleted: inserted && giftStatus === 'completed',
      becameFailed: inserted && giftStatus === 'failed',
    };
  }

  if (client) {
    const existing = await client`
      SELECT * FROM donations WHERE transaction_id = ${transactionId} LIMIT 1
    `;
    if (existing.length) {
      const prior = existing[0] as Record<string, unknown>;
      if (giftStatus === 'completed' && String(prior.status) !== 'completed') {
        await client`
          UPDATE donations SET
            status = 'completed',
            amount = ${input.amount},
            fee_covered = ${input.feeCovered},
            fee_amount = ${feeAmount},
            total_charged = ${totalCharged},
            payment_method = ${input.paymentMethod},
            stripe_payment_intent_id = COALESCE(${input.stripePaymentIntentId || null}, stripe_payment_intent_id),
            next_billing_date = COALESCE(${nextBillingDate}, next_billing_date)
          WHERE transaction_id = ${transactionId}
        `;
        await refreshDonorAggregates(String(prior.donor_id));
      } else if (giftStatus === 'failed' && String(prior.status) === 'pending') {
        await client`
          UPDATE donations SET status = 'failed' WHERE transaction_id = ${transactionId}
        `;
      }
      const donor = (await findDonorByEmailNeon(email))!;
      const row = await client`SELECT * FROM donations WHERE transaction_id = ${transactionId} LIMIT 1`;
      return {
        donor,
        donation: mapDonationRow(row[0] as Record<string, unknown>),
        mode,
        inserted: false,
        becameCompleted: giftStatus === 'completed' && String(prior.status) !== 'completed',
        becameFailed: giftStatus === 'failed' && String(prior.status) === 'pending',
      };
    }

    let donor = await findDonorByEmailNeon(email);
    if (donor) {
      const recurringActive = input.frequency !== 'one-time' ? true : donor.recurringActive;
      const stripeCustomerId = input.stripeCustomerId || donor.stripeCustomerId || null;
      await client`
        UPDATE donors SET
          name = ${isAnonymous ? donor.name : displayName},
          address = ${input.donorAddress || donor.address},
          last_gift_date = ${timestamp},
          recurring_active = ${recurringActive},
          recurring_amount = ${input.frequency !== 'one-time' ? input.amount : donor.recurringAmount ?? null},
          recurring_frequency = ${input.frequency !== 'one-time' ? input.frequency : donor.recurringFrequency ?? null},
          stripe_customer_id = COALESCE(${stripeCustomerId}, stripe_customer_id),
          stripe_subscription_id = COALESCE(${input.stripeSubscriptionId || null}, stripe_subscription_id),
          updated_at = NOW()
        WHERE id = ${donor.id}
      `;
      donor = (await findDonorByEmailNeon(email))!;
    } else {
      const donorId = `donor-${Date.now()}`;
      await client`
        INSERT INTO donors (
          id, name, email, phone, address, lifetime_giving, total_gifts_count,
          first_gift_date, last_gift_date, recurring_active, recurring_amount,
          recurring_frequency, gdpr_consent, gdpr_consent_date, stripe_customer_id
        ) VALUES (
          ${donorId},
          ${displayName},
          ${email},
          ${''},
          ${input.donorAddress || ''},
          ${0},
          ${0},
          ${timestamp},
          ${timestamp},
          ${input.frequency !== 'one-time'},
          ${input.frequency !== 'one-time' ? input.amount : null},
          ${input.frequency !== 'one-time' ? input.frequency : null},
          ${true},
          ${timestamp},
          ${input.stripeCustomerId || null}
        )
      `;
      donor = (await findDonorByEmailNeon(email))!;
    }

    await client`
      INSERT INTO donations (
        id, transaction_id, receipt_number, donor_id, donor_name, donor_email, donor_address,
        amount, fee_covered, fee_amount, total_charged, frequency, fund_id, fund_name, fund_code,
        payment_method, card_brand, card_last4, status, dedication, is_anonymous, contributed_at,
        next_billing_date, stripe_payment_intent_id, plaid_transfer_id, plaid_institution,
        plaid_account_mask, awc_dcb_voucher, awc_synced, encrypted_token, envelope_number
      ) VALUES (
        ${donationId},
        ${transactionId},
        ${receiptNumber},
        ${donor.id},
        ${displayName},
        ${email},
        ${input.donorAddress || null},
        ${input.amount},
        ${input.feeCovered},
        ${feeAmount},
        ${totalCharged},
        ${input.frequency},
        ${input.fundId},
        ${input.fundName},
        ${fundCode},
        ${input.paymentMethod},
        ${input.cardBrand || null},
        ${input.cardLast4 || null},
        ${giftStatus},
        ${input.dedication || null},
        ${isAnonymous},
        ${timestamp},
        ${nextBillingDate || null},
        ${input.stripePaymentIntentId || null},
        ${null},
        ${null},
        ${null},
        ${input.awcDcbVoucher || null},
        ${Boolean(input.awcSynced)},
        ${''},
        ${null}
      )
    `;

    if (giftStatus === 'completed') {
      await refreshDonorAggregates(donor.id);
      donor = (await findDonorByEmailNeon(email))!;
    }
    const donationRows = await client`
      SELECT * FROM donations WHERE id = ${donationId} LIMIT 1
    `;
    return {
      donor,
      donation: mapDonationRow(donationRows[0] as Record<string, unknown>),
      mode,
      inserted: true,
      becameCompleted: giftStatus === 'completed',
      becameFailed: giftStatus === 'failed',
    };
  }

  if (!memoryStoreAllowed()) {
    throw new Error('DATABASE_URL is required unless DEV_MEMORY_STORE=true');
  }

  // Memory fallback (opt-in via DEV_MEMORY_STORE)
  const existingMem = memoryDonations.find((d) => d.transactionId === transactionId);
  if (existingMem) {
    const wasCompleted = existingMem.status === 'completed';
    const wasPending = existingMem.status === 'pending';
    if (giftStatus === 'completed' && existingMem.status !== 'completed') {
      existingMem.status = 'completed';
      existingMem.amount = input.amount;
      existingMem.feeCovered = Boolean(input.feeCovered);
      existingMem.feeAmount = feeAmount;
      existingMem.totalCharged = totalCharged;
      existingMem.paymentMethod = input.paymentMethod;
      existingMem.stripePaymentIntentId =
        input.stripePaymentIntentId || existingMem.stripePaymentIntentId;
      existingMem.nextBillingDate =
        nextBillingDate || existingMem.nextBillingDate;
      const owner = memoryDonors.get(existingMem.donorId);
      if (owner) {
        const rows = memoryDonations.filter((d) => d.donorId === owner.id && d.status === 'completed');
        owner.lifetimeGiving = rows.reduce((s, d) => s + d.amount, 0);
        owner.totalGiftsCount = rows.length;
      }
    } else if (giftStatus === 'failed' && wasPending) {
      existingMem.status = 'failed';
    }
    const donor = findDonorByEmailMemory(email)!;
    return {
      donor,
      donation: existingMem,
      mode,
      inserted: false,
      becameCompleted: giftStatus === 'completed' && !wasCompleted,
      becameFailed: giftStatus === 'failed' && wasPending,
    };
  }

  let donor = findDonorByEmailMemory(email);
  if (donor) {
    donor = {
      ...donor,
      name: isAnonymous ? donor.name : displayName,
      address: input.donorAddress || donor.address,
      lastGiftDate: timestamp,
      recurringActive: input.frequency !== 'one-time' ? true : donor.recurringActive,
      recurringAmount: input.frequency !== 'one-time' ? input.amount : donor.recurringAmount,
      recurringFrequency: input.frequency !== 'one-time' ? input.frequency : donor.recurringFrequency,
    };
    memoryDonors.set(donor.id, donor);
  } else {
    donor = {
      id: `donor-${Date.now()}`,
      name: displayName,
      email,
      phone: '',
      address: input.donorAddress || '',
      lifetimeGiving: 0,
      totalGiftsCount: 0,
      firstGiftDate: timestamp,
      lastGiftDate: timestamp,
      recurringActive: input.frequency !== 'one-time',
      recurringAmount: input.frequency !== 'one-time' ? input.amount : undefined,
      recurringFrequency: input.frequency !== 'one-time' ? input.frequency : undefined,
      gdprConsent: true,
      gdprConsentDate: timestamp,
    };
    memoryDonors.set(donor.id, donor);
  }

  const donation: StoredDonation = {
    id: donationId,
    transactionId,
    receiptNumber,
    donorId: donor.id,
    donorName: displayName,
    donorEmail: email,
    donorAddress: input.donorAddress,
    amount: input.amount,
    feeCovered: Boolean(input.feeCovered),
    feeAmount,
    totalCharged,
    frequency: input.frequency,
    fundId: input.fundId,
    fundName: input.fundName,
    fundCode,
    paymentMethod: input.paymentMethod,
    cardBrand: input.cardBrand,
    cardLast4: input.cardLast4,
    status: giftStatus,
    refundedAmount: 0,
    dedication: input.dedication,
    isAnonymous,
    timestamp,
    nextBillingDate: nextBillingDate || undefined,
    stripePaymentIntentId: input.stripePaymentIntentId,
    awcDcbVoucher: input.awcDcbVoucher,
    awcSynced: Boolean(input.awcSynced),
    encryptedToken: '',
  };
  memoryDonations.unshift(donation);
  if (giftStatus === 'completed') {
    const rows = memoryDonations.filter((d) => d.donorId === donor.id && d.status === 'completed');
    donor.lifetimeGiving = rows.reduce((s, d) => s + d.amount, 0);
    donor.totalGiftsCount = rows.length;
    memoryDonors.set(donor.id, donor);
  }
  return {
    donor,
    donation,
    mode,
    inserted: true,
    becameCompleted: giftStatus === 'completed',
    becameFailed: giftStatus === 'failed',
  };
}

export async function listGiftsByEmail(email: string): Promise<{
  donor: StoredDonor | null;
  donations: StoredDonation[];
  mode: 'neon' | 'memory';
}> {
  const normalized = normalizeEmail(email);
  if (!normalized.includes('@')) {
    return { donor: null, donations: [], mode: giftStoreMode() };
  }

  const client = getSql();
  if (client) {
    const donor = await findDonorByEmailNeon(normalized);
    const rows = await client`
      SELECT * FROM donations
      WHERE LOWER(donor_email) = ${normalized}
      ORDER BY contributed_at DESC
    `;
    return {
      donor,
      donations: rows.map((r) => mapDonationRow(r as Record<string, unknown>)),
      mode: 'neon',
    };
  }

  requireMemoryGifts();
  const donor = findDonorByEmailMemory(normalized);
  const donations = memoryDonations.filter((d) => normalizeEmail(d.donorEmail) === normalized);
  return { donor, donations, mode: 'memory' };
}

/** Staff ledger — recent gifts across all donors (Neon or memory). */
export async function listAllGifts(limit = 500): Promise<{
  donations: StoredDonation[];
  donors: StoredDonor[];
  mode: 'neon' | 'memory';
}> {
  const safeLimit = Math.min(Math.max(Number(limit) || 500, 1), 2000);
  const client = getSql();
  if (client) {
    const donationRows = await client`
      SELECT * FROM donations
      ORDER BY contributed_at DESC
      LIMIT ${safeLimit}
    `;
    const donorRows = await client`
      SELECT * FROM donors
      ORDER BY last_gift_date DESC NULLS LAST
      LIMIT ${safeLimit}
    `;
    return {
      donations: donationRows.map((r) => mapDonationRow(r as Record<string, unknown>)),
      donors: donorRows.map((r) => mapDonorRow(r as Record<string, unknown>)),
      mode: 'neon',
    };
  }

  requireMemoryGifts();
  const donations = [...memoryDonations]
    .sort((a, b) => b.timestamp.localeCompare(a.timestamp))
    .slice(0, safeLimit);
  const donors = [...memoryDonors.values()].slice(0, safeLimit);
  return { donations, donors, mode: 'memory' };
}

export async function applyGiftRefund(input: {
  stripePaymentIntentId?: string | null;
  invoiceId?: string | null;
  amountRefunded: number;
  pgClient?: pg.PoolClient;
}): Promise<StoredDonation | null> {
  const pi = String(input.stripePaymentIntentId || '').trim();
  const invoiceId = String(input.invoiceId || '').trim();
  const gift =
    (pi ? await getGiftByTransactionId(pi, input.pgClient) : null) ||
    (invoiceId ? await getGiftByTransactionId(invoiceId, input.pgClient) : null);
  if (!gift) return null;
  const amountRefunded = Math.max(
    0,
    Number(input.amountRefunded) > 0 ? Number(input.amountRefunded) : gift.amount
  );
  const fullyRefunded = amountRefunded + 0.0001 >= gift.amount;
  const nextStatus: StoredDonation['status'] = fullyRefunded ? 'refunded' : gift.status === 'failed' ? gift.status : 'completed';
  if (input.pgClient) {
    const updated = await input.pgClient.query(
      `UPDATE donations
       SET refunded_amount = $2,
           status = CASE WHEN $3 THEN 'refunded' ELSE status END
       WHERE id = $1
       RETURNING *`,
      [gift.id, amountRefunded, fullyRefunded]
    );
    if (fullyRefunded) {
      await refreshDonorAggregatesInTransaction(input.pgClient, gift.donorId);
    }
    return updated.rows[0] ? mapDonationRow(updated.rows[0] as Record<string, unknown>) : { ...gift, refundedAmount: amountRefunded, status: nextStatus };
  }
  const client = getSql();
  if (client) {
    const rows = await client`
      UPDATE donations
      SET refunded_amount = ${amountRefunded},
          status = CASE WHEN ${fullyRefunded} THEN 'refunded' ELSE status END
      WHERE id = ${gift.id}
      RETURNING *
    `;
    if (fullyRefunded) await refreshDonorAggregates(gift.donorId);
    return rows[0] ? mapDonationRow(rows[0] as Record<string, unknown>) : { ...gift, refundedAmount: amountRefunded, status: nextStatus };
  }
  requireMemoryGifts();
  gift.refundedAmount = amountRefunded;
  if (fullyRefunded) gift.status = 'refunded';
  if (fullyRefunded) {
    const donor = memoryDonors.get(gift.donorId);
    if (donor) {
      const completed = memoryDonations.filter((row) => row.donorId === donor.id && row.status === 'completed');
      donor.lifetimeGiving = completed.reduce((sum, row) => sum + row.amount, 0);
      donor.totalGiftsCount = completed.length;
    }
  }
  return gift;
}

export async function updateGiftStatusByStripePi(
  paymentIntentId: string,
  status: StoredDonation['status'],
  pgClient?: pg.PoolClient
): Promise<{ updated: boolean; mode: 'neon' | 'memory' }> {
  const pi = String(paymentIntentId || '').trim();
  if (!pi) return { updated: false, mode: giftStoreMode() };

  if (pgClient) {
    const rows = await pgClient.query(
      `UPDATE donations
       SET status = $2
       WHERE (stripe_payment_intent_id = $1 OR transaction_id = $1)
         AND ($2 <> 'failed' OR status <> 'completed')
         AND ($2 <> 'refunded' OR status = 'completed')
       RETURNING donor_id`,
      [pi, status]
    );
    if (status === 'completed' || status === 'refunded') {
      for (const row of rows.rows) {
        await refreshDonorAggregatesInTransaction(pgClient, String(row.donor_id));
      }
    }
    return { updated: rows.rowCount > 0, mode: 'neon' };
  }

  const client = getSql();
  if (client) {
    const rows = await client`
      UPDATE donations
      SET status = ${status}
      WHERE stripe_payment_intent_id = ${pi}
         OR transaction_id = ${pi}
      RETURNING id
    `;
    if (rows.length && (status === 'completed' || status === 'refunded')) {
      const donors = await client`
        SELECT donor_id FROM donations WHERE stripe_payment_intent_id = ${pi} OR transaction_id = ${pi}
      `;
      for (const row of donors) {
        await refreshDonorAggregates(String(row.donor_id));
      }
    }
    return { updated: rows.length > 0, mode: 'neon' };
  }

  requireMemoryGifts();
  let updated = false;
  for (const d of memoryDonations) {
    if (d.stripePaymentIntentId === pi || d.transactionId === pi) {
      const wasCompleted = d.status === 'completed';
      d.status = status;
      if (wasCompleted && status !== 'completed') {
        const donor = memoryDonors.get(d.donorId);
        if (donor) {
          const completed = memoryDonations.filter(
            (gift) => gift.donorId === donor.id && gift.status === 'completed'
          );
          donor.lifetimeGiving = completed.reduce((sum, gift) => sum + gift.amount, 0);
          donor.totalGiftsCount = completed.length;
        }
      }
      updated = true;
    }
  }
  return { updated, mode: 'memory' };
}

export async function getGiftByTransactionId(
  transactionId: string,
  pgClient?: pg.PoolClient
): Promise<StoredDonation | null> {
  const id = String(transactionId || '').trim();
  if (!id) return null;
  if (pgClient) {
    const rows = await pgClient.query(
      `SELECT * FROM donations
       WHERE transaction_id = $1 OR stripe_payment_intent_id = $1
       LIMIT 1`,
      [id]
    );
    if (!rows.rows.length) return null;
    return mapDonationRow(rows.rows[0] as Record<string, unknown>);
  }
  const client = getSql();
  if (client) {
    const rows = await client`
      SELECT * FROM donations
      WHERE transaction_id = ${id} OR stripe_payment_intent_id = ${id}
      LIMIT 1
    `;
    if (!rows.length) return null;
    return mapDonationRow(rows[0] as Record<string, unknown>);
  }
  requireMemoryGifts();
  return (
    memoryDonations.find((d) => d.transactionId === id || d.stripePaymentIntentId === id) || null
  );
}

const memoryReceiptClaims = new Set<string>();

/**
 * Atomically claim the right to send a receipt email for this gift.
 * Returns claimed:false if already sent or gift missing.
 */
export async function claimReceiptEmailSend(transactionId: string): Promise<{
  claimed: boolean;
  reason?: 'duplicate' | 'missing';
  gift?: StoredDonation;
}> {
  const id = String(transactionId || '').trim();
  if (!id) return { claimed: false, reason: 'missing' };

  const client = getSql();
  if (client) {
    const rows = await client`
      UPDATE donations
      SET receipt_email_sent_at = NOW()
      WHERE (transaction_id = ${id} OR stripe_payment_intent_id = ${id})
        AND status = 'completed'
        AND receipt_email_sent_at IS NULL
      RETURNING *
    `;
    if (!rows.length) {
      const existing = await getGiftByTransactionId(id);
      if (!existing) return { claimed: false, reason: 'missing' };
      return { claimed: false, reason: 'duplicate' };
    }
    return { claimed: true, gift: mapDonationRow(rows[0] as Record<string, unknown>) };
  }

  requireMemoryGifts();
  const gift = memoryDonations.find(
    (d) => d.transactionId === id || d.stripePaymentIntentId === id
  );
  if (!gift || gift.status !== 'completed') return { claimed: false, reason: 'missing' };
  if (memoryReceiptClaims.has(gift.transactionId)) {
    return { claimed: false, reason: 'duplicate' };
  }
  memoryReceiptClaims.add(gift.transactionId);
  return { claimed: true, gift };
}

export async function findDonorByEmail(email: string): Promise<StoredDonor | null> {
  const client = getSql();
  if (client) return findDonorByEmailNeon(email);
  requireMemoryGifts();
  return findDonorByEmailMemory(email);
}

export async function setDonorStripeCustomerId(
  email: string,
  stripeCustomerId: string
): Promise<void> {
  const normalized = normalizeEmail(email);
  const client = getSql();
  if (client) {
    await client`
      UPDATE donors
      SET stripe_customer_id = ${stripeCustomerId}, updated_at = NOW()
      WHERE LOWER(email) = ${normalized}
    `;
    return;
  }
  requireMemoryGifts();
  const donor = findDonorByEmailMemory(normalized);
  if (donor) donor.stripeCustomerId = stripeCustomerId;
}

export async function markSubscriptionInactive(
  subscriptionId: string,
  pgClient?: pg.PoolClient
): Promise<void> {
  const id = String(subscriptionId || '').trim();
  if (!id) return;
  if (pgClient) {
    await pgClient.query(
      'UPDATE donors SET recurring_active = FALSE, updated_at = NOW() WHERE stripe_subscription_id = $1',
      [id]
    );
    return;
  }
  const client = getSql();
  if (client) {
    await client`
      UPDATE donors SET recurring_active = FALSE, updated_at = NOW()
      WHERE stripe_subscription_id = ${id}
    `;
    return;
  }
  requireMemoryGifts();
  for (const donor of memoryDonors.values()) {
    if (donor.stripeSubscriptionId === id) donor.recurringActive = false;
  }
}
